export const flags = [
    { image: 'images/ad.svg', name: 'Afghanistan', id: 1 },
    { image: 'images/al.svg', name: 'Albania', id: 2 },
    { image: 'images/dz.svg', name: 'Algeria', id: 3 },
    { image: 'images/andorra.svg', name: 'Andorra', id: 4 },
    { image: 'images/ao.svg', name: 'Angola', id: 5 },
    { image: 'images/ag.svg', name: 'Antigua and Barbuda', id: 6 },
    { image: 'images/ar.svg', name: 'Argentina', id: 7 },
    { image: 'images/am.svg', name: 'Armenia', id: 8 },
    { image: 'images/au.svg', name: 'Australia', id: 9 },
    { image: 'images/at.svg', name: 'Austria', id: 10 },
    { image: 'images/az.svg', name: 'Azerbaijan', id: 11 },
    { image: 'images/bh.svg', name: 'Bahrain', id: 12 },
    { image: 'images/bd.svg', name: 'Bangladesh', id: 13 },
    { image: 'images/by.svg', name: 'Belarus', id: 14 },
    { image: 'images/be.svg', name: 'Belgium', id: 15 },
    { image: 'images/bz.svg', name: 'Belize', id: 16 },
    { image: 'images/bo.svg', name: 'Bolivia', id: 17 },
    { image: 'images/br.svg', name: 'Brazil', id: 18 },
    { image: 'images/bw.svg', name: 'Botswana', id: 19 },
    { image: 'images/bn.svg', name: 'Brunei', id: 20 },
    { image: 'images/bg.svg', name: 'Bulgaria', id: 21 },
    { image: 'images/bf.svg', name: 'Burkina Faso', id: 22 },
    { image: 'images/bi.svg', name: 'Burundi', id: 23 },
    { image: 'images/cv.svg', name: 'Cabo Verde', id: 24 },
    { image: 'images/cm.svg', name: 'Cameroon', id: 25 },
    { image: 'images/ca.svg', name: 'Canada', id: 26 },
    { image: 'images/ky.svg', name: 'Cayman Islands', id: 27 },
    { image: 'images/cf.svg', name: 'Central African Republic', id: 28 },
    { image: 'images/td.svg', name: 'Chad', id: 29 },
    { image: 'images/cl.svg', name: 'Chile', id: 30 },
    { image: 'images/cn.svg', name: 'China', id: 31 },
    { image: 'images/co.svg', name: 'Colombia', id: 32 },
    { image: 'images/km.svg', name: 'Comoros', id: 33 },
    { image: 'images/cg.svg', name: 'Congo', id: 34 },
    { image: 'images/cr.svg', name: 'Costa Rica', id: 35 },
    { image: 'images/hr.svg', name: 'Croatia', id: 36 },
    { image: 'images/cu.svg', name: 'Cuba', id: 37 },
    { image: 'images/cy.svg', name: 'Cyprus', id: 38 },
    { image: 'images/cz.svg', name: 'Czech Republic', id: 39 },
    { image: 'images/dk.svg', name: 'Denmark', id: 40 },
    { image: 'images/dj.svg', name: 'Djibouti', id: 41 },
    { image: 'images/dm.svg', name: 'Dominica', id: 42 },
    { image: 'images/do.svg', name: 'Dominican Republic', id: 43 },
    { image: 'images/ec.svg', name: 'Ecuador', id: 44 },
    { image: 'images/eg.svg', name: 'Egypt', id: 45 },
    { image: 'images/sv.svg', name: 'El Salvador', id: 46 },
    { image: 'images/eq.svg', name: 'Equatorial Guinea', id: 47 },
    { image: 'images/er.svg', name: 'Eritrea', id: 48 },
    { image: 'images/ee.svg', name: 'Estonia', id: 49 },
    { image: 'images/et.svg', name: 'Ethiopia', id: 50 },
    { image: 'images/fo.svg', name: 'Faroe Islands', id: 51 },
    { image: 'images/fj.svg', name: 'Fiji', id: 52 },
    { image: 'images/fi.svg', name: 'Finland', id: 53 },
    { image: 'images/fr.svg', name: 'France', id: 54 },
    { image: 'images/gf.svg', name: 'French Guiana', id: 55 },
    { image: 'images/pf.svg', name: 'French Polynesia', id: 56 },
    { image: 'images/ga.svg', name: 'Gabon', id: 57 },
    { image: 'images/gm.svg', name: 'Gambia', id: 58 },
    { image: 'images/ge.svg', name: 'Georgia', id: 59 },
    { image: 'images/de.svg', name: 'Germany', id: 60 },
    { image: 'images/gh.svg', name: 'Ghana', id: 61 },
    { image: 'images/gr.svg', name: 'Greece', id: 62 },
    { image: 'images/gt.svg', name: 'Guatemala', id: 63 },
    { image: 'images/gn.svg', name: 'Guinea', id: 64 },
    { image: 'images/gw.svg', name: 'Guinea-Bissau', id: 65 },
    { image: 'images/gy.svg', name: 'Guyana', id: 66 },
    { image: 'images/ht.svg', name: 'Haiti', id: 67 },
    { image: 'images/hn.svg', name: 'Honduras', id: 68 },
    { image: 'images/hk.svg', name: 'Hong Kong', id: 69 },
    { image: 'images/hu.svg', name: 'Hungary', id: 70 },
    { image: 'images/is.svg', name: 'Iceland', id: 71 },
    { image: 'images/in.svg', name: 'India', id: 72 },
    { image: 'images/id.svg', name: 'Indonesia', id: 73 },
    { image: 'images/ir.svg', name: 'Iran', id: 74 },
    { image: 'images/iq.svg', name: 'Iraq', id: 75 },
    { image: 'images/ie.svg', name: 'Ireland', id: 76 },
    { image: 'images/il.svg', name: 'Israel', id: 77 },
    { image: 'images/it.svg', name: 'Italy', id: 78 },
    { image: 'images/jm.svg', name: 'Jamaica', id: 79 },
    { image: 'images/jp.svg', name: 'Japan', id: 80 },
    { image: 'images/jo.svg', name: 'Jordan', id: 81 },
    { image: 'images/kz.svg', name: 'Kazakhstan', id: 82 },
    { image: 'images/ke.svg', name: 'Kenya', id: 83 },
    { image: 'images/ki.svg', name: 'Kiribati', id: 84 },
    { image: 'images/kw.svg', name: 'Kuwait', id: 85 },
    { image: 'images/kg.svg', name: 'Kyrgyzstan', id: 86 },
    { image: 'images/la.svg', name: 'Laos', id: 87 },
    { image: 'images/lv.svg', name: 'Latvia', id: 88 },
    { image: 'images/lb.svg', name: 'Lebanon', id: 89 },
    { image: 'images/ls.svg', name: 'Lesotho', id: 90 },
    { image: 'images/lr.svg', name: 'Liberia', id: 91 },
    { image: 'images/ly.svg', name: 'Libya', id: 92 },
    { image: 'images/li.svg', name: 'Liechtenstein', id: 93 },
    { image: 'images/lt.svg', name: 'Lithuania', id: 94 },
    { image: 'images/lu.svg', name: 'Luxembourg', id: 95 },
    { image: 'images/mk.svg', name: 'North Macedonia', id: 96 },
    { image: 'images/mg.svg', name: 'Madagascar', id: 97 },
    { image: 'images/mw.svg', name: 'Malawi', id: 98 },
    { image: 'images/my.svg', name: 'Malaysia', id: 99 },
    { image: 'images/mv.svg', name: 'Maldives', id: 100 },
    { image: 'images/ml.svg', name: 'Mali', id: 101 },
    { image: 'images/mt.svg', name: 'Malta', id: 102 },
    { image: 'images/mh.svg', name: 'Marshall Islands', id: 103 },
    { image: 'images/mq.svg', name: 'Martinique', id: 104 },
    { image: 'images/mr.svg', name: 'Mauritania', id: 105 },
    { image: 'images/ms.svg', name: 'Montserrat', id: 106 },
    { image: 'images/ma.svg', name: 'Morocco', id: 107 },
    { image: 'images/mz.svg', name: 'Mozambique', id: 108 },
    { image: 'images/mm.svg', name: 'Myanmar', id: 109 },
    { image: 'images/na.svg', name: 'Namibia', id: 110 },
    { image: 'images/np.svg', name: 'Nepal', id: 111 },
    { image: 'images/nl.svg', name: 'Netherlands', id: 112 },
    { image: 'images/nc.svg', name: 'New Caledonia', id: 113 },
    { image: 'images/pg.svg', name: 'Papua New Guinea', id: 114 },
    { image: 'images/pk.svg', name: 'Pakistan', id: 115 },
    { image: 'images/pl.svg', name: 'Poland', id: 116 },
    { image: 'images/pt.svg', name: 'Portugal', id: 117 },
    { image: 'images/pr.svg', name: 'Puerto Rico', id: 118 },
    { image: 'images/qa.svg', name: 'Qatar', id: 119 },
    { image: 'images/re.svg', name: 'Réunion', id: 120 },
    { image: 'images/ro.svg', name: 'Romania', id: 121 },
    { image: 'images/ru.svg', name: 'Russia', id: 122 },
    { image: 'images/rw.svg', name: 'Rwanda', id: 123 },
    { image: 'images/sa.svg', name: 'Saudi Arabia', id: 124 },
    { image: 'images/sn.svg', name: 'Senegal', id: 125 },
    { image: 'images/rs.svg', name: 'Serbia', id: 126 },
    { image: 'images/sc.svg', name: 'Seychelles', id: 127 },
    { image: 'images/sl.svg', name: 'Sierra Leone', id: 128 },
    { image: 'images/sg.svg', name: 'Singapore', id: 129 },
    { image: 'images/sx.svg', name: 'Sint Maarten', id: 130 },
    { image: 'images/sk.svg', name: 'Slovakia', id: 131 },
    { image: 'images/si.svg', name: 'Slovenia', id: 132 },
    { image: 'images/sb.svg', name: 'Solomon Islands', id: 133 },
    { image: 'images/so.svg', name: 'Somalia', id: 134 },
    { image: 'images/za.svg', name: 'South Africa', id: 135 },
    { image: 'images/kr.svg', name: 'South Korea', id: 136 },
    { image: 'images/es.svg', name: 'Spain', id: 137 },
    { image: 'images/lk.svg', name: 'Sri Lanka', id: 138 },
    { image: 'images/kn.svg', name: 'Saint Kitts and Nevis', id: 139 },
    { image: 'images/lc.svg', name: 'Saint Lucia', id: 140 },
    { image: 'images/sv.svg', name: 'Saint Vincent and the Grenadines', id: 141 },
    { image: 'images/sd.svg', name: 'Sudan', id: 142 },
    { image: 'images/sr.svg', name: 'Suriname', id: 143 },
    { image: 'images/sj.svg', name: 'Svalbard and Jan Mayen', id: 144 },
    { image: 'images/sz.svg', name: 'Eswatini', id: 145 },
    { image: 'images/se.svg', name: 'Sweden', id: 146 },
    { image: 'images/ch.svg', name: 'Switzerland', id: 147 },
    { image: 'images/sy.svg', name: 'Syria', id: 148 },
    { image: 'images/tw.svg', name: 'Taiwan', id: 149 },
    { image: 'images/tj.svg', name: 'Tajikistan', id: 150 },
    { image: 'images/tz.svg', name: 'Tanzania', id: 151 },
    { image: 'images/th.svg', name: 'Thailand', id: 152 },
    { image: 'images/tl.svg', name: 'Timor-Leste', id: 153 },
    { image: 'images/tg.svg', name: 'Togo', id: 154 },
    { image: 'images/to.svg', name: 'Tonga', id: 155 },
    { image: 'images/tt.svg', name: 'Trinidad and Tobago', id: 156 },
    { image: 'images/tn.svg', name: 'Tunisia', id: 157 },
    { image: 'images/tr.svg', name: 'Turkey', id: 158 },
    { image: 'images/tm.svg', name: 'Turkmenistan', id: 159 },
    { image: 'images/ug.svg', name: 'Uganda', id: 160 },
    { image: 'images/ua.svg', name: 'Ukraine', id: 161 },
    { image: 'images/ae.svg', name: 'United Arab Emirates', id: 162 },
    { image: 'images/gb.svg', name: 'United Kingdom', id: 163 },
    { image: 'images/uy.svg', name: 'Uruguay', id: 164 },
    { image: 'images/uz.svg', name: 'Uzbekistan', id: 165 },
    { image: 'images/ve.svg', name: 'Venezuela', id: 166 },
    { image: 'images/vn.svg', name: 'Vietnam', id: 167 },
    { image: 'images/wf.svg', name: 'Wallis and Futuna', id: 168 },
    { image: 'images/ye.svg', name: 'Yemen', id: 169 },
    { image: 'images/zm.svg', name: 'Zambia', id: 170 },
    { image: 'images/zw.svg', name: 'Zimbabwe', id: 171 }
];
